[build]
  publish = "."
  command = "echo 'static site'"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public,max-age=3600"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
